#!/system/bin/sh
# sy

# All hail busybox for standardising this script!
busybox=/sbin/.core/busybox
oPATH=$PATH
PATH=$busybox:$oPATH
set -o pipefail

# Check if run under root --------------------------------
if ! ls /data > /dev/null 2> /dev/null; then
    echo "[!] ERROR"
    echo "    ts-binds needs to be invoked"
    echo "    from an elevated shell."
    echo "    Please run 'su' first."
    echo
    echo "Terminating.."
    exit 1
fi

# Functions ----------------------------------------------
MODDIR=/sbin/.core/img/ts-binds
datadir=/data/ts-binds
int=/mnt/runtime/default/emulated/0
obb=/mnt/runtime/default/emulated/obb
intraw=/data/media/0
sdname=$(grep -m 1 "/mnt/media_rw/" /proc/mounts | grep -m 1 -Eo "[0-9A-Z]{4}-[0-9A-Z]{4}")
sd=/mnt/runtime/default/$sdname
sdraw=/mnt/media_rw/$sdname
legacy=false
folderlist=$datadir/cached-folderlist.sh
folderlistuser=$intraw/ts-binds-folderlist.txt

if [ -f $datadir/legacy ]; then
    legacy=true
    int=$intraw
    obb=/data/media/obb
    sd=$sdraw
fi

supass() {
    /sbin/su -M -c "$*"
}

printhelp() {
    echo "tsbinds [options] [arg]"
    echo
    echo "Available options:"
    echo
    echo "help ............... Show this reference text"
    echo "h | --help | -h .... Ditto"
    echo "pairs .............. Prints out the folder"
    echo "                     pairs in folderlist"
    echo "bind <pair name> ... Binds a specific pair"
    echo "                     entry by its name"
    echo "bind o <src> <des> . Binds <src> to <des>"
    echo "bind all ........... Binds all entries "
    echo "bind o <src> <des> . Binds <src> to <des>"
    echo "unbind <pair name> . Unbinds a specific pair"
    echo "                     entry by its name"
    echo "unbind all ......... Unbinds all entries"
    echo "unbind o <des> ..... Unbinds <des>"
    echo "check <pair name> .. Check if an entry is binded"
    echo "check all .......... Check if all entries are"
    echo "                     individually binded"
    echo "update ............. Update cached entries if"
    echo "                     the user's entries are"
    echo "                     modified"
    echo "update f ........... Update cached entries"
    echo "                     regardless if the user's"
    echo "                     entries are modified"
    echo "reinit ............. Re-run the script that"
    echo "                     runs on boot"
    echo "disable ............ Disables automatic "
    echo "                     mounting on boot"
    echo "enable ............. Enables automatic "
    echo "                     mounting on boot"
    echo "mode ............... Output what mode is being"
    echo "                     used"
    echo "mode <arg> ......... Modes:"
    echo "                     'default' uses SDCardFS"
    echo "                     'legacy'  uses FUSE"
    echo "                     'device'  uses device default"
    echo "reset .............. Resets ts-binds."
    echo "                     folderlist won't be affected."

    echo
}

abort() {
    echo "$*"
    exit 1
}

# No action given ----------------------------------------
if [ ! "$1" ]; then
    echo "E: No action is declared!"
    echo ''
    printhelp

# Print Help ---------------------------------------------
elif [ "$1" = "help" ] || [ "$1" = "h" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    printhelp

# Bind ---------------------------------------------------
elif [ "$1" = "bind" ]; then
    folderbind() {
        if supass mountpoint -q \""$3"\"; then
            echo "$1 is already binded"
        elif [ ! -d "$2" ] && [ ! -f "$2" ]; then
            abort "Bind aborted: Path \"$2\" as source doesn't exist!"
        elif [ ! -d "$3" ] && [ ! -f "$3" ]; then
            abort "Bind aborted: Path \"$3\" as target doesn't exist!"
        else
            echo "Binding $1"
            if supass mount --rbind \""$2"\" \""$3"\"; then
                if ! $legacy; then
                    runtimeread="$(echo "$3" | sed 's/\/mnt\/runtime\/default/\/mnt\/runtime\/read/g')"
                    runtimewrite="$(echo "$3" | sed 's/\/mnt\/runtime\/default/\/mnt\/runtime\/write/g')"
                    remountOK=true
                    if echo "$3" | grep -Eq "${int}|${obb}"; then
                        $remountOK && { supass mount -o remount,gid=9997,mask=6 \""$runtimeread"\" || remountOK=false; }
                        $remountOK && { supass mount -o remount,gid=9997,mask=6 \""$runtimewrite"\" || remountOK=false; }
                    elif echo "$3" | grep -q "$sd"; then
                        echo "In progress"
                    fi
                    if ! $remountOK; then
                        tsbinds unbind o "$3"
                        abort "Bind remount failed and unbinded $1"
                    fi
                fi
            else
                abort "Bind failed"
            fi
        fi
    }
    if [ ! "$2" ]; then
        abort 'E: Bind name is not provided!'
    elif [ "$2" = "all" ]; then
        echo "Binding all entries"
        . $folderlist
        echo "All entries were processed"
    elif [ "$2" = "o" ]; then
        folderbind "o" "$3" "$4"
    elif line="$(grep -m 1 "$2" $folderlist)"; then
        $line
    else
        abort "Unable to bind \"$2\", entry not found in list!"
    fi

# Unbind -------------------------------------------------
elif [ "$1" = "unbind" ]; then
    folderbind() {
        if ! supass mountpoint -q \""$3"\"; then
            echo "$1 is already unbinded"
        else
            echo "Unbinding $1"
            if ! supass umount \""$3"\"; then
                abort "Unbind failed"
            fi
        fi
    }
    if [ ! "$2" ]; then
        abort 'E: Bind name is not provided!'
    elif [ "$2" = "all" ]; then
        echo "Unbinding all entries"
        . $folderlist
        echo "All entries were processed"
    elif [ "$2" = "o" ]; then
        folderbind "o" "$3" "$3"
    elif line="$(grep -m 1 "$2" $folderlist)"; then
        $line
    else
        abort "Unable to unbind $2, entry not found in list!"
    fi

# Check --------------------------------------------------
elif [ "$1" = "check" ]; then
    folderbind() {
        if supass mountpoint -q \""$3"\"
            then echo "$1 is BINDED"
            else echo "$1 is NOT binded"
        fi
    }
    if [ ! "$2" ]; then
        echo 'E: Bind name is not provided!'
    elif [ "$2" = "all" ]; then
        . $folderlist
        echo "All entries were checked"
    elif line="$(grep -m 1 "$2" $folderlist)"; then
        $line
    else
        abort "Unable to check $2, entry not found in list!"
    fi

# Update -------------------------------------------------
elif [ "$1" = "update" ]; then
    if [ ! -d $datadir ]; then
        cp -R $MODDIR/data $datadir
        echo "Copied data folder to /data"
        tsbinds update
    elif [ ! -f $folderlistuser ]; then
        cp $datadir/fresh-folderlist.txt $folderlistuser
        echo "Copied user list to internal storage"
        chown 1023:1023 $folderlistuser
        chmod 0664 $folderlistuser
        tsbinds update
    elif [ ! -f $folderlist ]; then
        cp $folderlistuser $folderlist
        echo "Cached the user list"
    elif [ "$2" ] && [ "$2" = "f" ]; then
        cp -f $folderlistuser $folderlist
        echo "Force-updated cached list"
    elif [ ! $folderlist -nt $folderlistuser ]; then
        echo "Difference found between cached and original user list"
        cp -f $folderlistuser $folderlist
        echo "Updated cached list"
    else
        echo "No update made to cached list"
    fi

# Reinit -------------------------------------------------
elif [ "$1" = "reinit" ]; then
    tsbinds unbind all
    $MODDIR/service.sh

# Enable or disable --------------------------------------
elif [ "$1" = "disable" ]; then
    if [ ! -f $datadir/disable ]; then
        touch $datadir/disable
        echo "ts-binds automatic bind disabled"
    else
        echo "Already disabled!"
    fi
elif [ "$1" = "enable" ]; then
    if [ ! -f $datadir/disable ]; then
        echo "Already enabled!"
    else
        rm -f $datadir/disable
        echo "ts-binds automatic bind enabled"
    fi

# Print folder pairs -------------------------------------
elif [ "$1" = "pairs" ]; then
    while IFS='' read -r line || [[ -n "$line" ]]; do
        if ! (echo "$line" | grep -Eo "#\| +" > /dev/null 2> /dev/null); then
            echo "$line" | awk '{print $2}'
        fi
    done < $folderlist

# Force change binding mode ------------------------------
elif [ "$1" = "mode" ]; then
    if [ ! "$2" ]; then
        $legacy && echo "FUSE" || echo "SDCardFS"
    elif [ "$2" = "default" ]; then
        echo "Forcing SDCardFS"
        if [ -f $datadir/legacy ]; then rm -f $datadir/legacy; fi
        echo "ro.sys.sdcardfs=true" > $MODDIR/system.prop
        echo "persist.sys.sdcardfs=force_on" >> $MODDIR/system.prop
        echo "persist.fuse_sdcard=false" >> $MODDIR/system.prop
    elif [ "$2" = "legacy" ]; then
        echo "Forcing FUSE"
        if [ ! -f $datadir/legacy ]; then touch $datadir/legacy; fi
        echo "ro.sys.sdcardfs=false" > $MODDIR/system.prop
        echo "persist.sys.sdcardfs=force_off" >> $MODDIR/system.prop
        echo "persist.fuse_sdcard=true" >> $MODDIR/system.prop
    elif [ "$2" = "device" ]; then
        echo "Setting Default"
        if [ -f $datadir/legacy-device ] && [ ! -f $datadir/legacy ]; then touch $datadir/legacy; fi
        if [ -f $MODDIR/system.prop ]; then rm -f $MODDIR/system.prop; fi
    else
        echo "Unknown parameter: $2!"
    fi

# Reset configs ------------------------------------------
elif [ "$1" = "reset" ]; then
    echo "Purging data folder"
    rm -Rf $datadir
    tsbinds update

# Take debug ---------------------------------------------
elif [ "$1" = "debug" ]; then
    debugdir=/cache/ts-binds-debug
    echo "Determining current debug position"
    if [ ! -f /cache/tsdebug ]; then
        echo "Starting fresh"
        echo "Assuming currently ts-binds not working correctly"
        if [ -d $debugdir ]; then
            rm -rf $debugdir/*
        else
            mkdir -p $debugdir
        fi
        echo "Getting mounts"
        supass cat /proc/mounts > $debugdir/ts-mounts-post.txt
        echo "Getting props"
        getprop > $debugdir/ts-props-post.txt
        echo "Getting log"
        cp $datadir/ts-binds.log $debugdir/ts-binds-post.log
        echo "Getting folderlist"
        cp $folderlist $debugdir/folderlist-post.txt
        echo "Getting module prop"
        cp $MODDIR/module.prop $debugdir/module.prop
        echo "Setting hint that debug phase 1 completed"
        touch /cache/tsdebug
        echo "Disabling ts-binds auto mount"
        tsbinds disable
        echo
        echo "NOTE: PLEASE REBOOT DEVICE AND RUN tsbinds debug AGAIN!"
    else
        echo "Starting second phase"
        echo "Getting mounts"
        supass cat /proc/mounts > $debugdir/ts-mounts-pre.txt
        echo "Getting props"
        getprop > $debugdir/ts-props-pre.txt
        echo "Getting log"
        cp $datadir/ts-binds.log $debugdir/ts-binds-pre.log
        echo "Getting folderlist"
        cp $folderlist $debugdir/folderlist-pre.txt
        echo "Deleting hint"
        rm -f /cache/tsdebug
        echo "Enabling automount"
        tsbinds enable
        echo "Disabling module altogether on next reboot"
        touch $MODDIR/disable
        echo "Moving debug folder to internal storage"
        if [ -d $dataraw/ts-binds-debug ]; then
            rm -rf $dataraw/ts-binds-debug
        fi
        chown 1023:1023 $debugdir
        chmod 0664 $debugdir
        mv $debugdir $dataraw/
        echo "DONE. Please zip the folder ts-binds-debug in internal storage and upload as requested by the developer."
        echo "Reboot to disable ts-binds completely."
    fi

# Action unrecognised ------------------------------------
else
    echo "E: Unknown action \"$1\" supplied"
    echo 'Run "tsbinds h" or "tsbinds help" for help'
fi

# Return true if script reaches here ---------------------
exit 0